// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NálezníkASP;

#nullable disable

namespace NálezníkASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223091358_UserAddedMigration")]
    partial class UserAddedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NálezníkASP.Models.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AfterCleanPhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Coin")
                        .HasColumnType("bit");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FindingDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FindingPhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LocationLangtitude")
                        .HasColumnType("int");

                    b.Property<int>("LocationLatitude")
                        .HasColumnType("int");

                    b.Property<int?>("MintingYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nominal")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("findings");
                });
#pragma warning restore 612, 618
        }
    }
}
